### PR TITLE
Migrate benchmarks from ScalaMeter to JMH

### PR DESCRIPTION
**Pull request by andreas-schroeder**
allows reporting results in throughput numbers, which is easier to compare:

```
[info] Benchmark                     Mode  Cnt        Score        Error  Units
[info] Decoding.avro4sGenerated     thrpt   10  1245981,607 ± 240459,069  ops/s
[info] Decoding.avro4sHandrolled    thrpt   10  1389618,599 ± 120671,766  ops/s
[info] Decoding.avroSpecificRecord  thrpt   10  3911859,751 ± 194854,176  ops/s
[info] Encoding.avro4sGenerated     thrpt   10  3672834,701 ±  86391,003  ops/s
[info] Encoding.avro4sHandrolled    thrpt   10  4125855,352 ±  79112,214  ops/s
[info] Encoding.avroSpecificRecord  thrpt   10  5556027,447 ± 125238,922  ops/s
```

to run:

```
sbt benchmarks/jmh:run
```

### CODE REVIEW

**Comment by sksamuel** [comment]
nice, do you have numbers handy from 3.x ?

**Comment by andreas-schroeder** [comment]
For 3.1.1, the numbers are:

```
[info] Benchmark                  Mode  Cnt        Score        Error  Units
[info] Decoding.avro4sGenerated  thrpt   10   922060,602 ± 103797,837  ops/s
[info] Encoding.avro4sGenerated  thrpt   10  1201985,930 ± 155101,365  ops/s
```

So 4.0.x is a 35% speedup in decoding, and a 205% speedup in encodig.

**Comment by sksamuel** [comment]
Not too bad eh :)

**Comment by sksamuel** [comment]
Feel free to merge whenever you're happy.

**Pull request merged**
