### PR TITLE
Fix recursive schema

### LINKED ISSUE #250: Recusrive schemas don't work in latest version
Trying the example in the README https://github.com/sksamuel/avro4s#recursive-schemas and it doesn't compile.

### PR DESCRIPTION
**Pull request by dragisak**
Fixes #250 

While traversing the graph, cache schemas created so far.

Unfortunately, I had to make a API change to:
```scala
trait SchemaFor[T] {
    def schema(fieldMapper: FieldMapper, context: SchemaFor.Context): Schema
}
```

I am open to any suggestion on how to avoid exposing internal implementation like this.

### CODE REVIEW

**Comment by sksamuel** [comment]
Thanks for the PR.
Can you explain what the context is used for ?

**Comment by dragisak** [comment]
To allow recursive schemas, you have to cache all the Schema's seen so far. When you traverse object graph, if Schema for your name/namespace pair has already been created, you can stop traversal and use that cached Schema. That's how avro [SchemaBuilder](https://avro.apache.org/docs/current/api/java/org/apache/avro/SchemaBuilder.FieldBuilder.html#type-java.lang.String-java.lang.String-) does it.

I had to figure a way to pass around that schema cache. Simplest was to add `Context` parameter to `schema` method.

**Comment by sksamuel** [comment]
Where is SchemaFor.Context defined? I can't see that in your PR?

**Comment by dragisak** [comment]
Here https://github.com/sksamuel/avro4s/pull/437/files#diff-8a05235c28d1810859da3b817e7441c7R578-R585

**Comment by sksamuel** [comment]
Thanks for the replying @dragisak. I think github was doing that thing where it hides large diffs and I missed this.

So in magnolia, we have recursive support. Do you think it's better to use that, or pass the context around? We couldn't change the SchemaFor contract without bumping a major version.

**Comment by WesselVS** [comment]
I also created a workaround for this much needed feature. I have a slightly different approach, where I leave SchemaFor intact and introduce SchemaForRec to generate recursive definitions. This is not ideal, but for now, it serves my needs. #453

**Comment by sksamuel** [comment]
I feel like we should combine the approaches in #453 #426 #409 as a 4.0 release (allowing for breaking changes). What do you think ?

**Comment by dragisak** [comment]
Sounds good. :+1

**Comment by dragisak** [comment]
Closing this in favor of #453

**Pull request closed without merging**
