### PR TITLE
#127 - use decimal conversion for big decimal

### PR DESCRIPTION
**Pull request by max5599**
The change will break the compatibility with message produced with the current conversion.
Not sure how to document it, any idea?

### CODE REVIEW

**Comment by mwz** [comment]
Hi @sksamuel, would you be able to merge this PR and release a new version?

**Comment by vlovgr** [comment]
@sksamuel Any chance for a release with this soon?

**Comment by sksamuel** [comment]
Yes sorry, I'll publish.

**Comment by sksamuel** [comment]
1.8.0 is out.

**Pull request merged**
