### PR TITLE
Update magnolia to 0.17.0

### PR DESCRIPTION
**Pull request by leonardoam**
I had an issue using scio along with avro4s, they use different versions of magnolia.

I've bumped magnolia, ran tests, and everything seems fine. Let me know of any related issue.

### CODE REVIEW

**Comment by leonardoam** [comment]
Okay, CI seems to be broken. I will check it later.

**Comment by leonardoam** [comment]
Sorry, I see this is repeated with https://github.com/sksamuel/avro4s/pull/537, any updates on that?

**Comment by sksamuel** [comment]
I will fix for 0.17 this weekend and release an updated avro4s

**Comment by leonardoam** [comment]
OK, thanks!

**Comment by sksamuel** [comment]
Not having much luck getting magnolia 0.17 work atm.

**Comment by leonardoam** [comment]
Where do you think the problem is? Can I help with anything? I don't know much about how avro4s works.

**Comment by sksamuel** [comment]
The tests fail because of a class not found exception on jackson, which is just bizarre. Adding jackson in explicitly didn't help either.
@leonardoam

**Comment by sksamuel** [comment]
Mag 0.17 merged from another branch now and deployed as 4.0.3

**Pull request closed without merging**
