### PR TITLE
Fix serialization issues with coproduct and scala enum decoders

### LINKED ISSUE #484: Decoder for Scala enum is not serializable
Hi, I'm using Avro4s with Flink, and it would be very useful to make the Decoder for Scala enumeration serializable.

Example:
```
import WeekDay.WeekDay
import com.sksamuel.avro4s.Decoder

object WeekDay extends Enumeration {
  type WeekDay = Value
  val Mon, Tue, Wed, Thu, Fri, Sat, Sun = Value
}

object TestApp extends App {
  org.apache.flink.util.InstantiationUtil.serializeObject(Decoder[WeekDay])
}
```

Result:
```
Exception in thread "main" java.io.NotSerializableException: scala.reflect.runtime.JavaMirrors$JavaMirror
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:586)
	at TestApp$.delayedEndpoint$com$elevenfs$transactions$serdes$TestApp$1(TestApp.scala:12)
	at TestApp$delayedInit$body.apply(TestApp.scala:11)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at TestApp$.main(TestApp.scala:11)
	at TestApp.main(TestApp.scala)
```

Would it make sense to mark this field as transient lazy val: https://github.com/sksamuel/avro4s/blob/f8d40e4587a65dbed444e0631230ccc6076d357f/avro4s-core/src/main/scala/com/sksamuel/avro4s/Decoder.scala#L343

### LINKED ISSUE #485: Decoder for shapeless Coproduct is not serializable
Hi, I'm using Avro4s with Flink, and I think it would be very useful to make the Decoder for Scala shapeless coproduct serializable.

Example:
```
import com.sksamuel.avro4s.Decoder
import shapeless.{:+:, CNil}

object TestApp extends App {
  type ISB = Int :+: String :+: Boolean :+: CNil
  org.apache.flink.util.InstantiationUtil.serializeObject(Decoder[ISB])
}
```

Result:
```
Exception in thread "main" java.io.NotSerializableException: com.sksamuel.avro4s.SafeFrom$$anon$2
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:586)
	at TestApp$.delayedEndpoint$com$elevenfs$transactions$serdes$TestApp$1(TestApp.scala:8)
	at TestApp$delayedInit$body.apply(TestApp.scala:6)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at TestApp$.main(TestApp.scala:6)
	at TestApp.main(TestApp.scala)
```

Would it make sense to simply make `com.sksamuel.avro4s.SafeFrom` serializable?

### PR DESCRIPTION
**Pull request by andreas-schroeder**
Fixes #484 and Fixes #485

### CODE REVIEW

**Comment by sksamuel** [comment]
#491 supersedes this ?

**Comment by sksamuel** [comment]
Actually this could be merged as a 3.x release fix?

**Comment by andreas-schroeder** [comment]
Yes, this is the fix for 3.x. I've fixed it also on the 4.0.x branch

**Comment by andreas-schroeder** [comment]
@sksamuel do you want to merge this and do a 3.x release before I merge the 4.0.x branch to master?

**Comment by sksamuel** [comment]
Yep.

**Comment by sksamuel** [comment]
3.1.1 released.

**Pull request merged**
