### PR TITLE
#200

### PR DESCRIPTION
**Pull request by tmnd1991**
suffix  type arguments name to generic classes in order to avoid type name clash

### CODE REVIEW

**Comment by tmnd1991** [comment]
This is a PR for #200

**Comment by sksamuel** [comment]
That was quick. There's a conflict so I can't merge. Also am I right in seeing that the default is for this feature to be off ?

**Comment by tmnd1991** [comment]
I fixed the conflicts. Yes, the default is for the feature to be turned off. I can make it work the other way around if you think it is better. I think that leaving it off by default helps in case of an update without breaking "old" schemas. I would keep it disabled by default in 1.x.x and enable it by default on > 2.0.0.
What do you think?

**Comment by sksamuel** [comment]
I agree that is the best approach.

**Pull request merged**
