### PR TITLE
Removed unused imports

### PR DESCRIPTION
**Pull request by MateuszKubuszok**
This PR should fix issues I encondered in https://github.com/sksamuel/avro4s/issues/71. It adds unused import check to compiler and removes imports from macros.

### CODE REVIEW

**Comment by sksamuel** [comment]
Awesome!

**Comment by MateuszKubuszok** [comment]
:smile:

**Comment by sksamuel** [comment]
Released as 1.6.2 FYI

**Comment by MateuszKubuszok** [comment]
I saw, great thanks!

**Pull request merged**
