### PR TITLE
Pre-compute name mappings and schemas in encoder/decoders

### PR DESCRIPTION
**Pull request by andreas-schroeder**
Followup to #426 - rebased it on top of master.

### CODE REVIEW

**Comment by WesselVS** [comment]
Cool, nice work.

**Comment by andreas-schroeder** [comment]
@WesselVS thanks, looking forward to the recursive schema fix btw

**Comment by andreas-schroeder** [comment]
rebased on top of master once more, removed codecs due to issues with magnolia derivations, and reverted magnolia to 0.12.8 since later versions break value type support.

**Comment by andreas-schroeder** [comment]
superseded by #470

**Pull request closed without merging**
