### PR TITLE
Fixed encoding GenericRecord using AvroDataOutputStream

### PR DESCRIPTION
**Pull request by ikryvorotenko**
There's an issue with writing raw `GenericRecord` using `AvroDataOutputStream` caused by cast to `ImmutableRecord`.
The proposed solution just narrows the type of encoded entity to `GenericRecord`, since that's the most generic type required by `GenericDatumWriter[GenericRecord]`.

### CODE REVIEW

**Comment by sksamuel** [comment]
Nice job, thanks.

**Comment by ikryvorotenko** [comment]
@sksamuel, thanks. when do you plan to release 3.0.2?

**Comment by sksamuel** [comment]
3.0.2 has been released.

**Comment by bobbyrauchenberg** [comment]
Hi @sksamuel - not meaning to hassle you - but we can't see 3.0.2 anywhere (we're also waiting on this)

**Comment by sksamuel** [comment]
Sorry it didn't seem to sync. Try now.

**Comment by bobbyrauchenberg** [comment]
nice, thanks!

**Pull request merged**
