### PR TITLE
Fix #273

### LINKED ISSUE #273: Diverging implicit expansion for SchemaFor in Coproducts inside case classes
Hi @sksamuel, just found this while upgrading one project from `1.8.3` to `2.0.2` but seems its also reproducible in master.

Given this model:
```scala
case class Coproducts(cp: Int :+: String :+: Boolean :+: CNil)
case class CoproductOfCoproductsField(cp: Coproducts :+: Boolean :+: CNil)
```

Trying to get a `SchemaFor[CoproductOfCoproductsField]` gives you a diverging implicit error:
```
diverging implicit expansion for type com.sksamuel.avro4s.SchemaFor[com.sksamuel.avro4s.schema.CoproductOfCoproductsField]
```

You can see it here in action

https://github.com/sksamuel/avro4s/compare/master...fedefernandez:ff/coproducts-in-fields?expand=1

Do you know why this could be happen? Thanks

### PR DESCRIPTION
**Pull request by 2chilled**
Fixes #273 by using shapeless.Lazy at the right places.

### CODE REVIEW

**Comment by 2chilled** [comment]
@sksamuel Would be nice to have a bugfix release including this patch asap as it's a show stopper for us upgrading to avro4s 2.x.x

**Comment by 2chilled** [comment]
Ok, this fails (again) for 2.11. Unfortunately I have zero motivation fixing it. Will release locally.

**Comment by 2chilled** [comment]
Addition: Support mixed object and class coproducts.

**Comment by sksamuel** [comment]
This is great. I am also working on an upgrade at the moment.

**Comment by sksamuel** [comment]
You might want to take a look at https://github.com/sksamuel/avro4s/tree/wip/magnolia which is what might become version 3.0. This should have your fixes applied.

**Comment by sksamuel** [comment]
Do you want to try the 3.0 snapshot for 2.11 ?

**Comment by 2chilled** [comment]
Pretty busy this weekend, but sure I'll try 3.0 on Monday. Have you checked that something similar to Github273.scala tests is green for 3.0? Is there a plan for 3.0 release somewhere?

**Comment by sksamuel** [comment]
Github273 has it's own unit test
https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/test/scala/com/sksamuel/avro4s/github/Github273.scala

And is green locally and on travis.

**Comment by sksamuel** [comment]
Master is now 3.0 btw.

**Comment by sksamuel** [comment]
I say that, it's green locally, failed on travis. But it's only because _:+: is not allowed in the avro name. I'll fix that now.

**Comment by sksamuel** [comment]
Green on travis now for 2.11 and 2.22
https://travis-ci.org/sksamuel/avro4s/builds/534123651

**Comment by 2chilled** [comment]
Sounds great! Let's forget about 2 and focus on 3 instead 👍

**Comment by sksamuel** [comment]
I've added comments to most outstanding issues. Once I get some feedback that 3.0 is working I will deploy a release candidate. The only issue is recursive schemas, but they didn't work properly in 2.0 either.

**Comment by 2chilled** [comment]
Just tried 3.0.0-RC2. Unfortunately Magnolia seems to be in a loop, constantly emitting `magnolia: could not find any direct subtypes of trait CNil` while trying to derive an `Encoder` instance for our ADT. The process eventually terminates with `java.lang.OutOfMemoryError: GC overhead limit exceeded`. This week I don't have much time for providing a minimization of the problem but I'll see what I can do.

**Comment by 2chilled** [comment]
@sksamuel Are you sure you want typeclass methods to consume `NamingStrategy` from implicit scope? In my experience, the best compromise is to exclusively mark typeclass instances (no matter if typeclass is algebraically lawful or not) implicit.

**Comment by sksamuel** [comment]
@2chilled I don't know what you mean by that. I need some way of passing `NamingStrategy` to the `ForSchema` macro.

**Comment by sksamuel** [comment]
How did you get on ?

**Comment by 2chilled** [comment]
@sksamuel All I'm suggesting is to transform e.g. `def decode(value: Any, schema: Schema)(implicit naming: NamingStrategy = DefaultNamingStrategy): T` to `def decode(value: Any, schema: Schema, naming: NamingStrategy = DefaultNamingStrategy): T` Maybe even get rid of the default value, for the reasons noted [here](http://www.wartremover.org/doc/warts.html) 

For the moment I released the latest 2.x.x (2.12) with my patches on our local repo. I'm hoping to get mentioned 3.x.x issue reproduced by next weekend. Our production ADT is pretty deep with mixed `sealed trait`s and `shapeless.Coproduct`s, should hopefully not be too much work to minimize.

**Comment by sksamuel** [comment]
I don't use wart remover myself so I assume this is the "wart" that you refer to:

```
ImplicitParameter
Implicit parameters as configuration often lead to confusing interfaces and can result in surprising inconsistencies.
```

It doesn't actually explain _why_ it is confusing. But that being said, I will see if I can remove the implicitness of the parameter. I had assumed I needed it to pass into the macro, but maybe I don't.

**Comment by sksamuel** [comment]
I have removed the implicit naming strategy from SchemaFor, Encoder and Decoder. They remain in the "entry" points of AvroSchema, ToRecord and FromRecord. See what you think.

**Comment by sksamuel** [comment]
Closing this as I believe it to be fixed in the 3.0 series and haven't heard otherwise.

**Pull request closed without merging**
