### PR TITLE
Handle generics when type is fully known

### PR DESCRIPTION
**Pull request by nightscape**
This is a first shot at handling generics.
I have only added a simple testcase, but it might well work for more complicated ones.
It would be great to get generic handling in some form into the next release! :smiley:

### CODE REVIEW

**Comment by nightscape** [comment]
For people interested in experimenting with this, you can try the Jitpack build of our fork.
Just add the following to your `build.sbt`
```scala
resolvers += "jitpack" at "https://jitpack.io"
libraryDependencies += "com.github.crealytics" % "avro4s" % "handle_generics-SNAPSHOT"

```

**Comment by nightscape** [comment]
Ok, I discovered a first caveat: The following will currently not work because of a name clash of the differently typed `Generic`s:
```scala
case class Generic[T](t: T)
case class SameGenericWithDifferentTypeArgs(gi: Generic[Int], gs: Generic[String])
val schema = SchemaFor[SameGenericWithDifferentTypeArgs]()
```
Does anyone know, would it be legal to name the types `Generic[Int]` and `Generic[String]` in the schema?

**Comment by nightscape** [comment]
Ok, according to the official Avro specs, only letters, numbers and underscores are allowed:
https://avro.apache.org/docs/1.8.1/spec.html#names
@sksamuel Do you know if the name generation has to be invertible? I.e. is the name parsed somewhere in order to get the class name?

**Comment by sksamuel** [comment]
Not that I can remember. I think you're OK to do something like
List__String__ to encode it.

**Comment by sksamuel** [comment]
Your work in this PR has been manually added to the 2.0.0 branch, so I will close this PR now. Thank you.

**Pull request closed without merging**
