### PR TITLE
adds scala 2.12 support & 2.11/2.12 cross-compilation settings

### PR DESCRIPTION
**Pull request by pjan**
As per title. Hope this helps in getting a release for 2.12 out soon. :pray:

### CODE REVIEW

**Comment by sksamuel** [comment]
Fingers crossed 2.12.1 fixes the macro issues.

**Comment by pjan** [comment]
Tested on local. All seems well.

**Comment by sksamuel** [comment]
Great

**Comment by sksamuel** [comment]
:+1:

**Comment by sksamuel** [comment]
Released as 1.6.3

**Pull request merged**
