### PR TITLE
Diverging implicit expansion for sealed case class

### PR DESCRIPTION
**Pull request by alexjg**
I can't figure out what's causing this so haven't got a fix yet, but this is a testcase for something that's biting me at the moment. Causes errors like this:

```
[error] <base dir>/avro4s/avro4s-core/src/test/scala/com/sksamuel/avro4s/record/encoder/SealedTraitEncoderTest.scala:70: diverging implicit expansion for type com.sksamuel.avro4s.SchemaFor[Outer]
[error] starting with macro method applyMacro in object SchemaFor
[error]     val schema = AvroSchema[Outer]
```

### CODE REVIEW

**Comment by sksamuel** [comment]
It will be related to #234

**Comment by alexjg** [comment]
So I've got a fix for the divergence problems but it's causing these weird `ClassNotFoundException`s in the tests.

**Comment by coltfred** [comment]
@alexjg Are you still working on this? I ran into this issue as well and eagerly await a fix so I can move to 2.x. Thank you to both you and @sksamuel for your work!

**Comment by sksamuel** [comment]
I've added your test case and got it working in 2.0.3
Can you try that version ?

**Comment by coltfred** [comment]
@sksamuel In my initial compilation, 2.0.3 seems to work for my use case. I'll spend some time today trying to do the full upgrade to the 2.x series and see if everything works well.

**Comment by sksamuel** [comment]
This should be working on master now (grab the latest snapshot).

**Comment by gregsilin** [comment]
@alexjg thanks for your work

@sksamuel is this a fix for https://github.com/sksamuel/avro4s/issues/254?  I may be getting things confused here.

**Comment by sksamuel** [comment]
254 is fixed in 3.0.x. You can test the latest snapshot by clicking on the badge on the homepage.

**Comment by gregsilin** [comment]
Great, thanks!

**Pull request closed without merging**
