### PR TITLE
Modernize the build; upgrade dependencies

### LINKED ISSUE #79: Modernize the build
The SBT docs [recommend using .sbt files](http://www.scala-sbt.org/0.13/docs/Full-Def.html) in favor of the "old" `project/*.scala` method. Also, I think the build could be cleaned up by creating `AutoPlugin`s for the global settings and for publishing. I'll issue a PR with these changes.

### PR DESCRIPTION
**Pull request by markschaake**
Resolves #79

Changes include:
- Upgrade SBT to 0.13.13
- Upgrade ScalaTest to 3.0.0 (from 3.0.0-RC3)
- Update .travis.yml to test on scala 2.11.8 and 2.12.0 instead of 2.11.7 and 2.12.0-M3
- Migrate to build.sbt
- Put common build settings in an AutoPlugin

### CODE REVIEW

**Comment by markschaake** [comment]
I see the build failed for scala 2.12.0. I don't have time to troubleshoot right now. Will look into it soon hopefully.

**Comment by sksamuel** [comment]
I've tried 2.12.0 too and it's completely  broken. It's related to one of
the last couple of commits perhaps.

**Comment by sksamuel** [comment]
Didn't work for me locally on 2.12.0 but wasn't this branch. I'll check out this branch and see.

**Comment by sksamuel** [comment]
Still errors when running this build locally.

**Comment by markschaake** [comment]
I see, this is the first time I've dealt with a cross-build issue. Sorry, I don't have time to troubleshoot the 2.12.0 build issues for now. Let's just leave this PR open, if you don't mind, for a while.

**Comment by sksamuel** [comment]
That's fine, I'll cherry pick bits of the PR until it starts to fail.

**Comment by sksamuel** [comment]
I've followed what you did here and it works. The error is as soon as you go to 2.12.0 it all collapses. 2.12.0-M4 works fine though.

**Pull request closed without merging**
